name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.11
  - ipykernel
  - snowflake-snowpark-python
  - pyopenssl=22.0.0
  - cachetools
  - pip
  - pip:
   # Snowflake
    - snowflake-cli==2.8.2
    - click==8.1.7
    - streamlit
    - matplotlib
    - seaborn
    - scikit-learn
    - joblib
    - pandas
